apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: hello.k8s.tatusl.xyz
    http:
      paths:
      - backend:
          serviceName: hello-world
          servicePort: 80
  - host: demo.k8s.tatusl.xyz
    http:
      paths:
      - backend:
          serviceName: go-demo
          servicePort: 80
